# Generated by Django 5.2.10 on 2026-06-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academique', '0003_remove_cours_coefficient_remove_seance_salle'),
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salle',
        ),
    ]
