# Generated by Django 5.2.10 on 2026-06-24 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academique', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='coefficient',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='salle',
        ),
    ]
